sudo: required
services:
  - docker

before_install:
  - docker build -t rlee1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rlee1/react-test npm test -- --coverage

after_success:
  - docker build -t rlee1/multi-client ./client
  - docker build -t rlee1/multi-nginx ./nginx
  - docker build -t rlee1/multi-server ./server
  - docker build -t rlee1/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push rlee1/multi-client
  - docker push rlee1/multi-nginx
  - docker push rlee1/multi-server
  - docker push rlee1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-269108589596
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
